# Generated by Django 5.2.3 on 2025-07-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0002_genre_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
